### PR TITLE
Fork adaptations

### PR DESCRIPTION
**Pull request by dmandalidis**
* No build for this PR (travis still disabled)
* OSSRH issue pending
* JAR signing?

### CODE REVIEW

**Comment by dmandalidis** [comment]
ping @davidxia

**Comment by dmandalidis** [comment]
@davidxia weren't you signing the JARs? (I didn't find something related in the codebase)

**Comment by davidxia** [comment]
Ah the release process was done manually most of the time on our laptops
with a command like

`mvn clean -Dgpg.keyname=$KEY_ID release:clean release:prepare
release:perform`

**Comment by dmandalidis** [comment]
@davidxia strange, from the initial .travis.yml I thought you were pushing the snapshots automatically (I guess these weren't signed or I didn't get something with UPLOAD_SONATYPE env var). Anyway, since maven gpg-travis integration is a little bit tricky, I 'll give it sometime to see if I can manage setting it automatically, otherwise I 'll merge it and release from local PC in the meanwhile.

Thanks

**Comment by dmandalidis** [comment]
@davidxia Done with automatic jar signing. Please have a final look so that I can :

* squash into one and merge
* rename this repo and re-push it to a new one along with its commit history. It seems that lots of github functionality is missing on forks (e.g. issues) since they 're intended for PRs only
* test travis build and release 1.0.0 so that you can update your links

**Pull request merged**
